// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tiops/common/models/workflow-resource.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceMode int32

const (
	ServiceMode_Nil     ServiceMode = 0
	ServiceMode_One     ServiceMode = 1
	ServiceMode_Replica ServiceMode = 2
)

var ServiceMode_name = map[int32]string{
	0: "Nil",
	1: "One",
	2: "Replica",
}

var ServiceMode_value = map[string]int32{
	"Nil":     0,
	"One":     1,
	"Replica": 2,
}

func (x ServiceMode) String() string {
	return proto.EnumName(ServiceMode_name, int32(x))
}

func (ServiceMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a052fcb2f97e11e6, []int{0}
}

type K8SAppType int32

const (
	K8SAppType_K8sDeployment K8SAppType = 0
	K8SAppType_K8sJob        K8SAppType = 1
)

var K8SAppType_name = map[int32]string{
	0: "K8sDeployment",
	1: "K8sJob",
}

var K8SAppType_value = map[string]int32{
	"K8sDeployment": 0,
	"K8sJob":        1,
}

func (x K8SAppType) String() string {
	return proto.EnumName(K8SAppType_name, int32(x))
}

func (K8SAppType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a052fcb2f97e11e6, []int{1}
}

type K8SContainer struct {
	Image                string            `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty" bson:"image"`
	Cmd                  []string          `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty" bson:"cmd"`
	Args                 []string          `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" bson:"args"`
	Env                  map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"env"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-"`
}

func (m *K8SContainer) Reset()         { *m = K8SContainer{} }
func (m *K8SContainer) String() string { return proto.CompactTextString(m) }
func (*K8SContainer) ProtoMessage()    {}
func (*K8SContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a052fcb2f97e11e6, []int{0}
}
func (m *K8SContainer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *K8SContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_K8SContainer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *K8SContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SContainer.Merge(m, src)
}
func (m *K8SContainer) XXX_Size() int {
	return m.Size()
}
func (m *K8SContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SContainer.DiscardUnknown(m)
}

var xxx_messageInfo_K8SContainer proto.InternalMessageInfo

func (m *K8SContainer) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *K8SContainer) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *K8SContainer) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *K8SContainer) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

type K8SPort struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	ContainerPort        int32    `protobuf:"varint,2,opt,name=containerPort,proto3" json:"containerPort,omitempty" bson:"containerPort"`
	ServicePort          int32    `protobuf:"varint,3,opt,name=servicePort,proto3" json:"servicePort,omitempty" bson:"servicePort"`
	NodePort             int32    `protobuf:"varint,4,opt,name=nodePort,proto3" json:"nodePort,omitempty" bson:"nodePort"`
	Proto                string   `protobuf:"bytes,5,opt,name=proto,proto3" json:"proto,omitempty" bson:"proto"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *K8SPort) Reset()         { *m = K8SPort{} }
func (m *K8SPort) String() string { return proto.CompactTextString(m) }
func (*K8SPort) ProtoMessage()    {}
func (*K8SPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_a052fcb2f97e11e6, []int{1}
}
func (m *K8SPort) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *K8SPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_K8SPort.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *K8SPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SPort.Merge(m, src)
}
func (m *K8SPort) XXX_Size() int {
	return m.Size()
}
func (m *K8SPort) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SPort.DiscardUnknown(m)
}

var xxx_messageInfo_K8SPort proto.InternalMessageInfo

func (m *K8SPort) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *K8SPort) GetContainerPort() int32 {
	if m != nil {
		return m.ContainerPort
	}
	return 0
}

func (m *K8SPort) GetServicePort() int32 {
	if m != nil {
		return m.ServicePort
	}
	return 0
}

func (m *K8SPort) GetNodePort() int32 {
	if m != nil {
		return m.NodePort
	}
	return 0
}

func (m *K8SPort) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

type K8SService struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	Ports                []*K8SPort `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty" bson:"ports"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" bson:"-"`
	XXX_unrecognized     []byte     `json:"-" bson:"-"`
	XXX_sizecache        int32      `json:"-" bson:"-"`
}

func (m *K8SService) Reset()         { *m = K8SService{} }
func (m *K8SService) String() string { return proto.CompactTextString(m) }
func (*K8SService) ProtoMessage()    {}
func (*K8SService) Descriptor() ([]byte, []int) {
	return fileDescriptor_a052fcb2f97e11e6, []int{2}
}
func (m *K8SService) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *K8SService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_K8SService.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *K8SService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SService.Merge(m, src)
}
func (m *K8SService) XXX_Size() int {
	return m.Size()
}
func (m *K8SService) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SService.DiscardUnknown(m)
}

var xxx_messageInfo_K8SService proto.InternalMessageInfo

func (m *K8SService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *K8SService) GetPorts() []*K8SPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

type K8SApp struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	ProjectId            string            `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty" bson:"projectId"`
	Replica              int32             `protobuf:"varint,3,opt,name=replica,proto3" json:"replica,omitempty" bson:"replica"`
	MainContainer        *K8SContainer     `protobuf:"bytes,4,opt,name=mainContainer,proto3" json:"mainContainer,omitempty" bson:"mainContainer"`
	WorkContainers       []*K8SContainer   `protobuf:"bytes,5,rep,name=workContainers,proto3" json:"workContainers,omitempty" bson:"workContainers"`
	InitContainers       []*K8SContainer   `protobuf:"bytes,6,rep,name=initContainers,proto3" json:"initContainers,omitempty" bson:"initContainers"`
	ServiceMode          ServiceMode       `protobuf:"varint,7,opt,name=serviceMode,proto3,enum=models.ServiceMode" json:"serviceMode,omitempty" bson:"serviceMode"`
	Datasets             map[string]string `protobuf:"bytes,8,rep,name=datasets,proto3" json:"datasets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"datasets"`
	ServiceTCPPorts      map[string]int32  `protobuf:"bytes,9,rep,name=serviceTCPPorts,proto3" json:"serviceTCPPorts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" bson:"serviceTCPPorts"`
	ServiceUDPPorts      map[string]int32  `protobuf:"bytes,10,rep,name=serviceUDPPorts,proto3" json:"serviceUDPPorts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" bson:"serviceUDPPorts"`
	Type                 K8SAppType        `protobuf:"varint,11,opt,name=type,proto3,enum=models.K8SAppType" json:"type,omitempty" bson:"type"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-"`
}

func (m *K8SApp) Reset()         { *m = K8SApp{} }
func (m *K8SApp) String() string { return proto.CompactTextString(m) }
func (*K8SApp) ProtoMessage()    {}
func (*K8SApp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a052fcb2f97e11e6, []int{3}
}
func (m *K8SApp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *K8SApp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_K8SApp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *K8SApp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SApp.Merge(m, src)
}
func (m *K8SApp) XXX_Size() int {
	return m.Size()
}
func (m *K8SApp) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SApp.DiscardUnknown(m)
}

var xxx_messageInfo_K8SApp proto.InternalMessageInfo

func (m *K8SApp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *K8SApp) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *K8SApp) GetReplica() int32 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *K8SApp) GetMainContainer() *K8SContainer {
	if m != nil {
		return m.MainContainer
	}
	return nil
}

func (m *K8SApp) GetWorkContainers() []*K8SContainer {
	if m != nil {
		return m.WorkContainers
	}
	return nil
}

func (m *K8SApp) GetInitContainers() []*K8SContainer {
	if m != nil {
		return m.InitContainers
	}
	return nil
}

func (m *K8SApp) GetServiceMode() ServiceMode {
	if m != nil {
		return m.ServiceMode
	}
	return ServiceMode_Nil
}

func (m *K8SApp) GetDatasets() map[string]string {
	if m != nil {
		return m.Datasets
	}
	return nil
}

func (m *K8SApp) GetServiceTCPPorts() map[string]int32 {
	if m != nil {
		return m.ServiceTCPPorts
	}
	return nil
}

func (m *K8SApp) GetServiceUDPPorts() map[string]int32 {
	if m != nil {
		return m.ServiceUDPPorts
	}
	return nil
}

func (m *K8SApp) GetType() K8SAppType {
	if m != nil {
		return m.Type
	}
	return K8SAppType_K8sDeployment
}

type WorkflowResources struct {
	Apps                 []*K8SApp `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty" bson:"apps"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *WorkflowResources) Reset()         { *m = WorkflowResources{} }
func (m *WorkflowResources) String() string { return proto.CompactTextString(m) }
func (*WorkflowResources) ProtoMessage()    {}
func (*WorkflowResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_a052fcb2f97e11e6, []int{4}
}
func (m *WorkflowResources) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WorkflowResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WorkflowResources.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WorkflowResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowResources.Merge(m, src)
}
func (m *WorkflowResources) XXX_Size() int {
	return m.Size()
}
func (m *WorkflowResources) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowResources.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowResources proto.InternalMessageInfo

func (m *WorkflowResources) GetApps() []*K8SApp {
	if m != nil {
		return m.Apps
	}
	return nil
}

func init() {
	proto.RegisterEnum("models.ServiceMode", ServiceMode_name, ServiceMode_value)
	proto.RegisterEnum("models.K8SAppType", K8SAppType_name, K8SAppType_value)
	proto.RegisterType((*K8SContainer)(nil), "models.K8sContainer")
	proto.RegisterMapType((map[string]string)(nil), "models.K8sContainer.EnvEntry")
	proto.RegisterType((*K8SPort)(nil), "models.K8sPort")
	proto.RegisterType((*K8SService)(nil), "models.K8sService")
	proto.RegisterType((*K8SApp)(nil), "models.K8sApp")
	proto.RegisterMapType((map[string]string)(nil), "models.K8sApp.DatasetsEntry")
	proto.RegisterMapType((map[string]int32)(nil), "models.K8sApp.ServiceTCPPortsEntry")
	proto.RegisterMapType((map[string]int32)(nil), "models.K8sApp.ServiceUDPPortsEntry")
	proto.RegisterType((*WorkflowResources)(nil), "models.WorkflowResources")
}

func init() {
	proto.RegisterFile("tiops/common/models/workflow-resource.proto", fileDescriptor_a052fcb2f97e11e6)
}

var fileDescriptor_a052fcb2f97e11e6 = []byte{
	// 658 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xae, 0xe3, 0x1c, 0xc7, 0x7f, 0xda, 0x74, 0xff, 0x0a, 0x59, 0x51, 0x89, 0xa2, 0x70, 0x50,
	0xd4, 0x82, 0x23, 0x05, 0x01, 0x56, 0xe1, 0xa6, 0x27, 0x21, 0x88, 0x0a, 0x95, 0x5b, 0xc4, 0xb5,
	0xeb, 0x2c, 0x91, 0xa9, 0xed, 0x5d, 0xed, 0x6e, 0x53, 0xe5, 0x0d, 0x78, 0x03, 0x78, 0x0f, 0x5e,
	0x82, 0x4b, 0x1e, 0x01, 0x95, 0x17, 0x41, 0xbb, 0x6b, 0xa7, 0x76, 0x65, 0x15, 0xf5, 0x6e, 0x67,
	0xe6, 0x9b, 0x6f, 0x66, 0xbe, 0xdd, 0x1d, 0xd8, 0x16, 0x21, 0xa1, 0x7c, 0x14, 0x90, 0x38, 0x26,
	0xc9, 0x28, 0x26, 0x53, 0x1c, 0xf1, 0xd1, 0x25, 0x61, 0xe7, 0x9f, 0x23, 0x72, 0xf9, 0x94, 0x61,
	0x4e, 0x2e, 0x58, 0x80, 0x1d, 0xca, 0x88, 0x20, 0xa8, 0xae, 0xe3, 0xdd, 0x7e, 0x59, 0x92, 0xb6,
	0x34, 0xb2, 0x1c, 0x21, 0xfc, 0xd9, 0x0c, 0x33, 0x8d, 0x18, 0xfc, 0x30, 0xe0, 0xbf, 0x89, 0xcb,
	0xf7, 0x49, 0x22, 0xfc, 0x30, 0xc1, 0x0c, 0x6d, 0x40, 0x2d, 0x8c, 0xfd, 0x19, 0xb6, 0x8d, 0xbe,
	0x31, 0x6c, 0x79, 0xda, 0x40, 0x1d, 0x30, 0x83, 0x78, 0x6a, 0x57, 0xfa, 0xe6, 0xb0, 0xe5, 0xc9,
	0x23, 0x42, 0x50, 0xf5, 0xd9, 0x8c, 0xdb, 0xa6, 0x72, 0xa9, 0x33, 0x1a, 0x81, 0x89, 0x93, 0xb9,
	0x5d, 0xed, 0x9b, 0x43, 0x6b, 0x7c, 0xdf, 0xd1, 0xf5, 0x9c, 0x3c, 0xbd, 0x73, 0x98, 0xcc, 0x0f,
	0x13, 0xc1, 0x16, 0x9e, 0x44, 0x76, 0x5f, 0x40, 0x33, 0x73, 0xc8, 0x12, 0xe7, 0x78, 0x91, 0x96,
	0x95, 0x47, 0xd9, 0xca, 0xdc, 0x8f, 0x2e, 0xb0, 0x5d, 0xd1, 0xad, 0x28, 0x63, 0xa7, 0xe2, 0x1a,
	0x83, 0x6f, 0x06, 0x34, 0x26, 0x2e, 0x3f, 0x26, 0x4c, 0xc8, 0x46, 0x12, 0x3f, 0xce, 0xfa, 0x55,
	0x67, 0xf4, 0x10, 0xda, 0x41, 0x56, 0x52, 0x82, 0x14, 0x43, 0xcd, 0x2b, 0x3a, 0x51, 0x1f, 0x2c,
	0x8e, 0xd9, 0x3c, 0x0c, 0xb0, 0xc2, 0x98, 0x0a, 0x93, 0x77, 0xa1, 0x2e, 0x34, 0x13, 0x32, 0xd5,
	0xe1, 0xaa, 0x0a, 0x2f, 0x6d, 0xd9, 0x9d, 0x92, 0xd0, 0xae, 0xe9, 0xee, 0xb4, 0x9e, 0x6f, 0x00,
	0x26, 0x2e, 0x3f, 0xd1, 0x1c, 0xa5, 0xbd, 0x3d, 0x82, 0x1a, 0x25, 0x4c, 0x70, 0x25, 0xa6, 0x35,
	0x5e, 0xcb, 0xc9, 0x24, 0x79, 0x3d, 0x1d, 0x1d, 0x7c, 0xad, 0x43, 0x7d, 0xe2, 0xf2, 0x5d, 0x4a,
	0x4b, 0x59, 0x36, 0xa1, 0x45, 0x19, 0xf9, 0x82, 0x03, 0xf1, 0x76, 0x9a, 0xea, 0x73, 0xed, 0x40,
	0x36, 0x34, 0x18, 0xa6, 0x51, 0x18, 0xf8, 0xe9, 0x54, 0x99, 0x89, 0x76, 0xa0, 0x1d, 0xfb, 0x61,
	0xb2, 0xbc, 0x10, 0x35, 0x96, 0x35, 0xde, 0x28, 0xbb, 0x2c, 0xaf, 0x08, 0x45, 0xaf, 0x61, 0x55,
	0x3e, 0xc9, 0xa5, 0x83, 0xdb, 0x35, 0x35, 0x42, 0x79, 0xf2, 0x0d, 0xac, 0xcc, 0x0e, 0x93, 0x50,
	0xe4, 0xb2, 0xeb, 0xb7, 0x65, 0x17, 0xb1, 0xe8, 0xf9, 0xf2, 0xae, 0x8e, 0xc8, 0x14, 0xdb, 0x8d,
	0xbe, 0x31, 0x5c, 0x1d, 0xff, 0x9f, 0xa5, 0x9e, 0x5c, 0x87, 0xbc, 0x3c, 0x0e, 0xb9, 0xd0, 0x9c,
	0xfa, 0xc2, 0xe7, 0x58, 0x70, 0xbb, 0xa9, 0xca, 0x6d, 0xe6, 0xca, 0xed, 0x52, 0xea, 0x1c, 0xa4,
	0x61, 0xfd, 0x2a, 0x97, 0x68, 0x74, 0x04, 0x6b, 0x29, 0xd1, 0xe9, 0xfe, 0xf1, 0xb1, 0xba, 0xb0,
	0x96, 0x22, 0x78, 0x70, 0x83, 0xe0, 0xa4, 0x88, 0xd2, 0x3c, 0x37, 0x73, 0x73, 0x74, 0x1f, 0x0f,
	0x52, 0x3a, 0xb8, 0x8d, 0x2e, 0x43, 0x15, 0xe9, 0x32, 0x2f, 0x7a, 0x0c, 0x55, 0xb1, 0xa0, 0xd8,
	0xb6, 0x94, 0x0e, 0xa8, 0xc8, 0x71, 0xba, 0xa0, 0xd8, 0x53, 0xf1, 0xee, 0x2b, 0x68, 0x17, 0x06,
	0xbc, 0xcb, 0x2f, 0xeb, 0xee, 0xc1, 0x46, 0xd9, 0x70, 0xff, 0xe2, 0xa8, 0x95, 0x73, 0x14, 0x26,
	0xba, 0x0b, 0xc7, 0xe0, 0x25, 0xac, 0x7f, 0x4a, 0x57, 0xa1, 0x97, 0x6e, 0x42, 0x8e, 0x06, 0x50,
	0xf5, 0x29, 0xe5, 0xb6, 0xa1, 0x54, 0x5c, 0x2d, 0x2a, 0xe0, 0xa9, 0xd8, 0xd6, 0x13, 0xb0, 0x72,
	0x2f, 0x03, 0x35, 0xc0, 0x7c, 0x1f, 0x46, 0x9d, 0x15, 0x79, 0xf8, 0x90, 0xe0, 0x8e, 0x81, 0x2c,
	0x68, 0x78, 0xfa, 0x63, 0x74, 0x2a, 0x5b, 0xdb, 0xea, 0xeb, 0xa6, 0xfa, 0xa1, 0x75, 0x68, 0x4f,
	0x5c, 0x7e, 0x80, 0x69, 0x44, 0x16, 0x31, 0x4e, 0x44, 0x67, 0x05, 0x81, 0xfa, 0x91, 0xef, 0xc8,
	0x59, 0xc7, 0xd8, 0x1b, 0xfe, 0xbc, 0xea, 0x19, 0xbf, 0xae, 0x7a, 0xc6, 0xef, 0xab, 0x9e, 0xf1,
	0xfd, 0x4f, 0x6f, 0x05, 0xee, 0x85, 0xc4, 0x51, 0xeb, 0xd6, 0x49, 0x57, 0xb0, 0xee, 0xe8, 0xac,
	0xae, 0x16, 0xc3, 0xb3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xe0, 0x11, 0xe8, 0xe3, 0x05,
	0x00, 0x00,
}

func (m *K8SContainer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *K8SContainer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *K8SContainer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Env) > 0 {
		for k := range m.Env {
			v := m.Env[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintWorkflowResource(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintWorkflowResource(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintWorkflowResource(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Args) > 0 {
		for iNdEx := len(m.Args) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Args[iNdEx])
			copy(dAtA[i:], m.Args[iNdEx])
			i = encodeVarintWorkflowResource(dAtA, i, uint64(len(m.Args[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Cmd) > 0 {
		for iNdEx := len(m.Cmd) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Cmd[iNdEx])
			copy(dAtA[i:], m.Cmd[iNdEx])
			i = encodeVarintWorkflowResource(dAtA, i, uint64(len(m.Cmd[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintWorkflowResource(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *K8SPort) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *K8SPort) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *K8SPort) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Proto) > 0 {
		i -= len(m.Proto)
		copy(dAtA[i:], m.Proto)
		i = encodeVarintWorkflowResource(dAtA, i, uint64(len(m.Proto)))
		i--
		dAtA[i] = 0x2a
	}
	if m.NodePort != 0 {
		i = encodeVarintWorkflowResource(dAtA, i, uint64(m.NodePort))
		i--
		dAtA[i] = 0x20
	}
	if m.ServicePort != 0 {
		i = encodeVarintWorkflowResource(dAtA, i, uint64(m.ServicePort))
		i--
		dAtA[i] = 0x18
	}
	if m.ContainerPort != 0 {
		i = encodeVarintWorkflowResource(dAtA, i, uint64(m.ContainerPort))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintWorkflowResource(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *K8SService) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *K8SService) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *K8SService) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Ports) > 0 {
		for iNdEx := len(m.Ports) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ports[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWorkflowResource(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintWorkflowResource(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *K8SApp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *K8SApp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *K8SApp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Type != 0 {
		i = encodeVarintWorkflowResource(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x58
	}
	if len(m.ServiceUDPPorts) > 0 {
		for k := range m.ServiceUDPPorts {
			v := m.ServiceUDPPorts[k]
			baseI := i
			i = encodeVarintWorkflowResource(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintWorkflowResource(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintWorkflowResource(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.ServiceTCPPorts) > 0 {
		for k := range m.ServiceTCPPorts {
			v := m.ServiceTCPPorts[k]
			baseI := i
			i = encodeVarintWorkflowResource(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintWorkflowResource(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintWorkflowResource(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.Datasets) > 0 {
		for k := range m.Datasets {
			v := m.Datasets[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintWorkflowResource(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintWorkflowResource(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintWorkflowResource(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.ServiceMode != 0 {
		i = encodeVarintWorkflowResource(dAtA, i, uint64(m.ServiceMode))
		i--
		dAtA[i] = 0x38
	}
	if len(m.InitContainers) > 0 {
		for iNdEx := len(m.InitContainers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InitContainers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWorkflowResource(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.WorkContainers) > 0 {
		for iNdEx := len(m.WorkContainers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WorkContainers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWorkflowResource(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.MainContainer != nil {
		{
			size, err := m.MainContainer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWorkflowResource(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Replica != 0 {
		i = encodeVarintWorkflowResource(dAtA, i, uint64(m.Replica))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ProjectId) > 0 {
		i -= len(m.ProjectId)
		copy(dAtA[i:], m.ProjectId)
		i = encodeVarintWorkflowResource(dAtA, i, uint64(len(m.ProjectId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintWorkflowResource(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WorkflowResources) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WorkflowResources) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WorkflowResources) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Apps) > 0 {
		for iNdEx := len(m.Apps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Apps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWorkflowResource(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintWorkflowResource(dAtA []byte, offset int, v uint64) int {
	offset -= sovWorkflowResource(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *K8SContainer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovWorkflowResource(uint64(l))
	}
	if len(m.Cmd) > 0 {
		for _, s := range m.Cmd {
			l = len(s)
			n += 1 + l + sovWorkflowResource(uint64(l))
		}
	}
	if len(m.Args) > 0 {
		for _, s := range m.Args {
			l = len(s)
			n += 1 + l + sovWorkflowResource(uint64(l))
		}
	}
	if len(m.Env) > 0 {
		for k, v := range m.Env {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovWorkflowResource(uint64(len(k))) + 1 + len(v) + sovWorkflowResource(uint64(len(v)))
			n += mapEntrySize + 1 + sovWorkflowResource(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *K8SPort) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovWorkflowResource(uint64(l))
	}
	if m.ContainerPort != 0 {
		n += 1 + sovWorkflowResource(uint64(m.ContainerPort))
	}
	if m.ServicePort != 0 {
		n += 1 + sovWorkflowResource(uint64(m.ServicePort))
	}
	if m.NodePort != 0 {
		n += 1 + sovWorkflowResource(uint64(m.NodePort))
	}
	l = len(m.Proto)
	if l > 0 {
		n += 1 + l + sovWorkflowResource(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *K8SService) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovWorkflowResource(uint64(l))
	}
	if len(m.Ports) > 0 {
		for _, e := range m.Ports {
			l = e.Size()
			n += 1 + l + sovWorkflowResource(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *K8SApp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovWorkflowResource(uint64(l))
	}
	l = len(m.ProjectId)
	if l > 0 {
		n += 1 + l + sovWorkflowResource(uint64(l))
	}
	if m.Replica != 0 {
		n += 1 + sovWorkflowResource(uint64(m.Replica))
	}
	if m.MainContainer != nil {
		l = m.MainContainer.Size()
		n += 1 + l + sovWorkflowResource(uint64(l))
	}
	if len(m.WorkContainers) > 0 {
		for _, e := range m.WorkContainers {
			l = e.Size()
			n += 1 + l + sovWorkflowResource(uint64(l))
		}
	}
	if len(m.InitContainers) > 0 {
		for _, e := range m.InitContainers {
			l = e.Size()
			n += 1 + l + sovWorkflowResource(uint64(l))
		}
	}
	if m.ServiceMode != 0 {
		n += 1 + sovWorkflowResource(uint64(m.ServiceMode))
	}
	if len(m.Datasets) > 0 {
		for k, v := range m.Datasets {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovWorkflowResource(uint64(len(k))) + 1 + len(v) + sovWorkflowResource(uint64(len(v)))
			n += mapEntrySize + 1 + sovWorkflowResource(uint64(mapEntrySize))
		}
	}
	if len(m.ServiceTCPPorts) > 0 {
		for k, v := range m.ServiceTCPPorts {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovWorkflowResource(uint64(len(k))) + 1 + sovWorkflowResource(uint64(v))
			n += mapEntrySize + 1 + sovWorkflowResource(uint64(mapEntrySize))
		}
	}
	if len(m.ServiceUDPPorts) > 0 {
		for k, v := range m.ServiceUDPPorts {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovWorkflowResource(uint64(len(k))) + 1 + sovWorkflowResource(uint64(v))
			n += mapEntrySize + 1 + sovWorkflowResource(uint64(mapEntrySize))
		}
	}
	if m.Type != 0 {
		n += 1 + sovWorkflowResource(uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *WorkflowResources) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Apps) > 0 {
		for _, e := range m.Apps {
			l = e.Size()
			n += 1 + l + sovWorkflowResource(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovWorkflowResource(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWorkflowResource(x uint64) (n int) {
	return sovWorkflowResource(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *K8SContainer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWorkflowResource
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: K8sContainer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: K8sContainer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cmd = append(m.Cmd, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Env == nil {
				m.Env = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWorkflowResource
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWorkflowResource
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWorkflowResource
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipWorkflowResource(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Env[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWorkflowResource(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *K8SPort) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWorkflowResource
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: K8sPort: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: K8sPort: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerPort", wireType)
			}
			m.ContainerPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContainerPort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServicePort", wireType)
			}
			m.ServicePort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServicePort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodePort", wireType)
			}
			m.NodePort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodePort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proto", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proto = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWorkflowResource(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *K8SService) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWorkflowResource
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: K8sService: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: K8sService: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ports = append(m.Ports, &K8SPort{})
			if err := m.Ports[len(m.Ports)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWorkflowResource(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *K8SApp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWorkflowResource
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: K8sApp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: K8sApp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replica", wireType)
			}
			m.Replica = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replica |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainContainer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MainContainer == nil {
				m.MainContainer = &K8SContainer{}
			}
			if err := m.MainContainer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkContainers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkContainers = append(m.WorkContainers, &K8SContainer{})
			if err := m.WorkContainers[len(m.WorkContainers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitContainers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitContainers = append(m.InitContainers, &K8SContainer{})
			if err := m.InitContainers[len(m.InitContainers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceMode", wireType)
			}
			m.ServiceMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServiceMode |= ServiceMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datasets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Datasets == nil {
				m.Datasets = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWorkflowResource
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWorkflowResource
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWorkflowResource
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipWorkflowResource(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Datasets[mapkey] = mapvalue
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceTCPPorts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ServiceTCPPorts == nil {
				m.ServiceTCPPorts = make(map[string]int32)
			}
			var mapkey string
			var mapvalue int32
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWorkflowResource
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWorkflowResource
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWorkflowResource
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipWorkflowResource(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ServiceTCPPorts[mapkey] = mapvalue
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceUDPPorts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ServiceUDPPorts == nil {
				m.ServiceUDPPorts = make(map[string]int32)
			}
			var mapkey string
			var mapvalue int32
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWorkflowResource
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWorkflowResource
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWorkflowResource
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipWorkflowResource(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthWorkflowResource
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ServiceUDPPorts[mapkey] = mapvalue
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= K8SAppType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWorkflowResource(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WorkflowResources) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWorkflowResource
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WorkflowResources: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WorkflowResources: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apps = append(m.Apps, &K8SApp{})
			if err := m.Apps[len(m.Apps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWorkflowResource(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWorkflowResource
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWorkflowResource(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWorkflowResource
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWorkflowResource
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWorkflowResource
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWorkflowResource
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWorkflowResource
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWorkflowResource        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWorkflowResource          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWorkflowResource = fmt.Errorf("proto: unexpected end of group")
)
